# CircleCI 2.1 GCP Orbs for CI/CD configuration file
#
# Check https://circleci.com/orbs/registry/?query=gcp for more details
#
version: 2.1
orbs:
  cloudrun: circleci/gcp-cloud-run@1.0.2
  gcr: circleci/gcp-gcr@0.7.1
jobs:
  build_test:
    docker:
      - image: circleci/python:3.7.4
    working_directory: ~/computer-vision-covid-19
    steps:
      - checkout
      - run:
          name: Install Python Dependencies
          command: |
            echo 'export PATH=~$PATH:~/.local/bin' >> $BASH_ENV && source $BASH_ENV
            pip install --user -r requirements.txt
      - run: 
          name: Copy secrets file
          commnd: |
            echo $SECRETS > ~/computer-vision-covid-19/app/lib/secrets.py
      - run:
          name: Run Tests
          command: |
            make test
      - run:
          name: Run Lint
          command: |
            make lint
workflows:
  version: 2.0
  test_build_deploy:
    jobs:
      - build_test:
          filters:
            branches:
              only:
                - master
 