# CircleCI 2.1 GCP Orbs for CI/CD configuration file
#
# Check https://circleci.com/orbs/registry/?query=gcp for more details
#
version: 2.1
orbs:
  cloudrun: circleci/gcp-cloud-run@1.0.2
  gcr: circleci/gcp-gcr@0.7.1
jobs:
  build_test:
    docker:
      - image: google/cloud-sdk
    working_directory: ~/computer-vision-covid-19
    steps:
      - checkout
      - run:
          name: Authorize Google SDK
          command: |
            echo $GCLOUD_SERVICE_KEY > ./GCLOUD_SERVICE_KEY.json | gcloud auth activate-service-account --key-file GCLOUD_SERVICE_KEY.json
            gcloud --quiet config set project $GOOGLE_PROJECT_ID
            gcloud --quiet config set compute/zone $GOOGLE_COMPUTE_ZONE
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            # Fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run:
          name: Install Dependencies
          command: |
            apt-get install python3-venv --yes
            python3 -m venv venv
            . venv/bin/activate
            pip3 install -r requirements.txt
      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}
      - run: 
          name: Copy secrets file
          command: |
            echo $SECRETS > ~/computer-vision-covid-19/app/lib/secrets.py
      # Run tests
      - run:
          name: Run Tests
          command: |
            . venv/bin/activate
            export GOOGLE_APPLICATION_CREDENTIALS='./GCLOUD_SERVICE_KEY.json'
            make test
      # Run lints
      - run:
          name: Run Lint
          command: |
            . venv/bin/activate
            make lint
workflows:
  test_build_deploy:
    jobs:
      - build_test:
          filters:
            branches:
              only:
                - master
 